before_script:
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - production

master_deploy:
  stage: production
  script:
    - ssh $SSH_USERNAME_PROD@$SSH_HOST_PROD "cd /var/lumi && git reset --hard HEAD && git checkout master && git pull origin master && docker run --rm --interactive --volume /var/lumi:/app composer install --ignore-platform-reqs --no-scripts && docker exec lum_php php artisan migrate:fresh --seed && exit"
  only:
    - master
