before_script:
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

stages:
  - production

master_deploy:
  stage: production
  script:
    - ssh $SSH_USERNAME_PROD@$SSH_HOST_PROD "cd /var/lumi && git reset --hard HEAD && git checkout master && git pull origin master && exit"
  only:
    - master
