before_script:
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - development

dev_deploy:
  stage: development
  script:
    - ssh $SSH_USERNAME_PROD@$SSH_HOST_PROD "cd /var/lumy
      && git reset --hard HEAD && git checkout master
      && git pull origin master
      && docker run --rm --interactive --volume /var/lumy:/app composer install --ignore-platform-reqs --no-scripts
      && docker run --rm --interactive --tty --volume ${PWD}:/app composer dump-autoload -o
      && docker exec lum_php php artisan cache:clear
      && docker exec lum_php php artisan route:cache
      && docker exec lum_php php artisan config:clear
      && docker exec lum_php php artisan view:clear
      && docker exec lum_php php artisan migrate:fresh --seed
      && exit
      "
  only:
    - master
