version: '3'

services:
  php-fpm:
    container_name: lum_php
    image: konstantinrjab/lumy
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ../:/var/www
  nginx:
    container_name: lum_nginx
    build:
      context: ./nginx
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
  mysql:
    container_name: lum_mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'lumy'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
#      - ../storage/logs:/var/log/mysql
#      - ./mysql:/etc/mysql/conf.d
      - lum_mysql:/var/lib/mysql
#  elk:
#    image: sebp/elk
#    container_name: lum_elk
##    volumes:
##      - ./elk/logstash/conf.d:/etc/logstash/conf.d
#    ports:
#      - "5601:5601"
#      - "9200:9200"
#      - "5044:5044"
#  filebeat:
#    image: elastic/filebeat:7.4.1
#    container_name: lum_filebeat
#    volumes:
#      - ../storage/logs:/etc/logs
##      - ./filebeat/:/usr/share/filebeat/
#    links:
#      - "elk"
#    depends_on:
#      - "elk"
    #entrypoint: ./time-to-start.sh
volumes:
  lum_mysql:
