version: '3'

services:
  php-fpm:
    container_name: lum_php
    image: konstantinrjab/lumy:prod
    volumes:
      - ../../:/var/www
    user: www-data
  nginx:
    container_name: lum_nginx
    build:
      context: ./nginx
    volumes:
      - ../../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - lum_certs:/etc/letsencrypt
      - lum_certs_data:/var/www/certbot
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
  mysql:
    container_name: lum_mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./mysql.env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ../../storage/logs:/var/log/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - lum_mysql:/var/lib/mysql
volumes:
  lum_mysql:
  lum_certs:
  lum_certs_data:
