filebeat:
  inputs:
  - type: log
    enabled: true
    paths:
      - "/etc/logs/api_datalogger_*.log"
    multiline.pattern: '^$'
    multiline.negate: true
    multiline.match: before

output.logstash:
  enabled: true
  hosts: ["elk:5044"]
  ssl:
    enabled: true
    certificate_authorities:
      - /etc/pki/tls/certs/logstash-beats.crt

# Debug logging config.
#logging.level: debug
#logging.selectors: ['*']
